import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React from 'react'

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>数据库查询</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.description}>
          查询数据库
        </p>
        <p className={styles.description}>
          18324034 林天皓
        </p>
        <div className={styles.grid}>
          <Link href="/posts/book">
            <a className={styles.card}>
              <h2>查询所有 BOOK &rarr;</h2>
            </a>
          </Link>
          <Link href="/posts/reader">
            <a className={styles.card}>
              <h2>查询所有 READER &rarr;</h2>
            </a>
          </Link>
          <Link href="/posts/record">
            <a className={styles.card}>
              <h2>查询所有 RECORD &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
